[package]
name = "timebay_client"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.8.0"
iced_wgpu = "0.9"
log = "0.4.17"
simple-log = "1.6.0"
paho-mqtt = "0.12.0"
thiserror = "1.0.38"
anyhow = "1.0.68"

timebay-common = { path = "../timebay-common" }